### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yashlikescode**
this closes issue #18 
image

### CODE REVIEW

**Comment by ridsuteri** [comment]
@kmryashasvi can u also add contributors to it?

**Comment by yashlikescode** [comment]
> @kmryashasvi can u also add contributors to it?

yes of course,
I will add another heading and list all 4 contributors along with me(i.e 5 contributors)
please look at the next comment for sample

**Comment by yashlikescode** [comment]
# Project maintainer:
Your profile will be mentioned here
# Project contributors:
Photos of contributors will be mentioned here

**Comment by yashlikescode** [comment]
What do you say, should i go forward?

**Comment by ridsuteri** [comment]
yes @kmryashasvi  go ahead

**Comment by yashlikescode** [comment]
Please have a look
image

**Comment by yashlikescode** [comment]
Feel free to interrupt me if you want some modifications

**Comment by ridsuteri** [comment]
@kmryashasvi looks great ! thanks for contributing

**Comment by yashlikescode** [comment]
in future (even after closing of crosswoc event), when you get new new contributors, 
tell me here  and I will add them in contributors section, you don't have to give me points for this, I will do it for free

**Comment by ridsuteri** [comment]
@kmryashasvi sure :)

**Pull request merged**
